CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(100) NOT NULL,
    image_url VARCHAR(255),
    -- Used decimal to avoid problems in potential database changes
    -- (don't use DOUBLE_PRECISION, it's specific from PostgreSQL)
    price DECIMAL(10,2) NOT NULL
);