CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    customer_uuid UUID NOT NULL,

    -- Has other side relation with order item
    CONSTRAINT customer_uuid_fk FOREIGN KEY (customer_uuid) REFERENCES customers(uuid)
);