CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    customer_uuid UUID NOT NULL,
    restaurant_uuid UUID NOT NULL,

    CONSTRAINT customer_uuid_fk FOREIGN KEY (customer_uuid) REFERENCES customers(uuid),
    CONSTRAINT restaurant_uuid_fk FOREIGN KEY (restaurant_uuid) REFERENCES restaurants(uuid)
);